# Generated by Django 4.0.4 on 2022-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='title',
            field=models.CharField(default='title', max_length=64),
            preserve_default=False,
        ),
    ]
