# Generated by Django 4.0.4 on 2022-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_api', '0002_lyrics_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='text',
            field=models.CharField(default='lyrics', max_length=2048),
            preserve_default=False,
        ),
    ]
