# Generated by Django 4.0.4 on 2022-04-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyrics_api', '0003_lyrics_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=128)),
                ('albumTitle', models.CharField(max_length=256)),
                ('albumArt', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=64)),
                ('media', models.CharField(max_length=256)),
                ('isPlayable', models.BooleanField(default=False)),
                ('preview', models.CharField(max_length=256)),
                ('lyrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics_api.lyrics')),
            ],
        ),
    ]
