# Generated by Django 4.0.4 on 2022-04-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_api', '0003_lyrics_text'),
        ('songs_api', '0002_alter_song_albumart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='albumTitle',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lyrics_api.lyrics'),
        ),
        migrations.AlterField(
            model_name='song',
            name='media',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
