# Generated by Django 4.0.4 on 2022-04-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_api', '0003_lyrics_text'),
        ('songs_api', '0003_alter_song_albumtitle_alter_song_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lyrics_api.lyrics'),
        ),
    ]
